import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {Script} from 'node:vm';
import {weaponStat,createWeaponUpgrades} from '../src/weapon-traits.js';
import {createTrainingDummy,ensureTrainingDummy,recordTrainingDamage,trainingDps,resetTrainingDamage} from '../src/training-dummy.js';
const source=await readFile(new URL('../src/game.js',import.meta.url),'utf8');
function production(name){const start=source.indexOf(`function ${name}(`);assert.ok(start>=0);const end=source.indexOf('\nfunction ',start+1);return source.slice(start,end<0?source.length:end);}
function api(names,context){new Script(names.map(production).join('\n')+'\nthis.api={'+names.join(',')+'};').runInNewContext(context);return context.api;}
test('lab keeps one persistent stationary target and clears hostiles',()=>{const game={nextId:1,player:{x:800,y:450},enemies:[{kind:'boss'}]};const dummy=ensureTrainingDummy(game);recordTrainingDamage(dummy,40,'pistol',1);game.player.x+=200;game.enemies.push({kind:'runner'});assert.equal(ensureTrainingDummy(game),dummy);assert.equal(game.enemies.length,1);assert.deepEqual([dummy.x,dummy.y],[980,360]);assert.equal(dummy.damageStats.total,40);assert.equal(dummy.speed,0);assert.equal(dummy.damage,0);});
test('damage records finite hits and rolling five-second DPS, then resets',()=>{const d=createTrainingDummy(1,0,0);for(const n of [NaN,Infinity,-2,0])assert.equal(recordTrainingDamage(d,n,'pistol',0),false);recordTrainingDamage(d,100,'pistol',1);recordTrainingDamage(d,50,'tank',4);assert.equal(trainingDps(d,5),30);assert.equal(trainingDps(d,6),10);assert.equal(trainingDps(d,10),0);assert.equal(d.damageStats.total,150);assert.equal(d.damageStats.hits,2);assert.equal(d.damageStats.bySource.tank,50);resetTrainingDamage(d);assert.equal(d.damageStats.total,0);assert.equal(d.damageStats.hits,0);assert.equal(d.damageStats.lastAt,null);});
test('production lethal damage preserves dummy health but kills ordinary enemies',()=>{const d=createTrainingDummy(1,0,0),normal={health:10};const f=api(['damageEnemy'],{game:{time:1},recordTrainingDamage,triggerEnemyHurt(){}});assert.equal(f.damageEnemy(d,1e9,'tank',.1),true);assert.equal(d.health,1000);assert.equal(d.damageStats.total,1e9);f.damageEnemy(normal,20,'pistol',0);assert.equal(normal.health,-10);});
test('shotgun hit counts without displacing target and freeze cap cannot execute it',()=>{const d=createTrainingDummy(1,30,40);const f=api(['damageEnemy','applyDirectBulletHit','resolveFreezeCap'],{game:{time:1},recordTrainingDamage,playerBulletDamage:b=>b.damage});const bullet={source:'shotgun',damage:25,knockback:true,vx:1,vy:0,life:1};assert.equal(f.applyDirectBulletHit(bullet,d),true);assert.deepEqual([d.x,d.y],[30,40]);assert.equal(bullet.life,0);assert.equal(d.damageStats.total,25);assert.equal(f.resolveFreezeCap(d,'ice'), 'none');assert.equal(d.health,1000);});
test('production enemy update records DOT without movement, attacks or summons',()=>{const d=createTrainingDummy(1,30,40);d.x=100;d.damageOverTime=[{dps:12,source:'flamethrower',expiresAt:5}];const game={time:1,enemies:[d],structures:[]};let summons;const f=api(['damageEnemy','updateEnemies'],{game,recordTrainingDamage,spawnBossRunners:n=>summons=n});f.updateEnemies(.5);assert.equal(d.damageStats.total,6);assert.deepEqual([d.x,d.y],[30,40]);assert.equal(d.health,1000);assert.equal(summons,0);game.time=6;f.updateEnemies(.5);assert.equal(d.damageStats.total,6);});

test('a base shotgun pellet deals more damage than a base pistol hit through the real damage path',()=>{const game={time:1,weaponUpgrades:createWeaponUpgrades()};const f=api(['pistolStats','shotgunStats','playerBulletDamage','damageEnemy','applyDirectBulletHit'],{game,weaponStat,recordTrainingDamage});const p=f.pistolStats(),s=f.shotgunStats();assert.equal(p.damage,32);assert.equal(s.damage,42);assert.ok(s.damage>p.damage);assert.equal(s.pellets*s.damage,378);const dummy=createTrainingDummy(1,0,0);for(let i=0;i<s.pellets;i++)f.applyDirectBulletHit({source:'shotgun',damage:s.damage,life:1},dummy);assert.equal(dummy.damageStats.total,378);assert.equal(dummy.health,1000);});
